//
//  DisplayMembersInteractor.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 2/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DisplayMembersBusinessLogic {
    func fetchMembers(request: DisplayMembers.Members.Request)
    func setCurrentMember(index: Int)
    func refreshMembers()
}

protocol DisplayMembersDataStore {
    var member: Member? {get set}
    var entity: Entity? {get set}
}


class DisplayMembersInteractor: DisplayMembersBusinessLogic, DisplayMembersDataStore {
    var presenter: DisplayMembersPresentationLogic?
    var entity: Entity?
    var member: Member?
    var members: [Member]?

    
    
    // MARK: VIP
    
    func fetchMembers(request: DisplayMembers.Members.Request) {
        self.members = [Member]()
        self.member = nil
        self.entity = request.entity
        self.members = request.entity?.members
        let response = DisplayMembers.Members.Response(members: self.members)
        self.presenter?.presentMembers(response: response)
    }
    
    
    func setCurrentMember(index: Int) {
        if members != nil {
            member = members![index]
        }
    }
    
    
    func refreshMembers() {
        self.members = entity?.members
        let response = DisplayMembers.Members.Response(members: self.members)
        self.presenter?.presentMembers(response: response)
    }
}
