//
//  DisplayDetailModels.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 6/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DisplayDetail {
  
    // MARK: Use cases
  
    enum Detail {
        struct Request {
        }
        struct Response {
            var selectedItem: SelectedItem?
        }
        struct ViewModel {
            var detailFields: [(String, String)]?
        }
    }

}


struct SelectedItem {
    var type: SelectedItemType?
    var entity: Entity?
    var member: Member?
    var meetingGroup: MeetingGroup?
    var event: Event?
}

enum SelectedItemType {
    case entity
    case member
    case meetingGroup
    case event
}
