//
//  DisplayDetailRouter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 6/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DisplayDetailRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol DisplayDetailDataPassing {
    var dataStore: DisplayDetailDataStore? { get }
}

class DisplayDetailRouter: NSObject, DisplayDetailRoutingLogic, DisplayDetailDataPassing {
    weak var viewController: DisplayDetailViewController?
    var dataStore: DisplayDetailDataStore?
  
  // MARK: Routing
  
  
}
