//
//  EditMeetingGroupModels.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 14/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum EditMeetingGroup {
  // MARK: Use cases
  
    enum MeetingGroup {
        struct Request {
        }
        struct Response {
            var members: [Member]?
        }
        struct ViewModel {
            var memberNames: String?
        }
    }
}
