//
//  EditMeetingGroupViewController.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 14/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditMeetingGroupDisplayLogic: class {
    func displayMemberNames(viewModel: EditMeetingGroup.MeetingGroup.ViewModel)
}



class EditMeetingGroupViewController: UIViewController, EditMeetingGroupDisplayLogic, EditMeetingGroupViewDelegate {
    
    var interactor: EditMeetingGroupBusinessLogic?
    var router: (NSObjectProtocol & EditMeetingGroupRoutingLogic & EditMeetingGroupDataPassing)?
    var sourceVC: DisplayMeetingGroupsViewController?
    var editView: EditMeetingGroupView?

    
    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    convenience init(sourceVC: DisplayMeetingGroupsViewController) {
        self.init(nibName:nil, bundle: nil)
        self.sourceVC = sourceVC
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    deinit {
        print("EditMeetingGroupViewController deinitialising")
    }
    
    

    // MARK: - Setup

    private func setup() {
        let viewController = self
        let interactor = EditMeetingGroupInteractor()
        let presenter = EditMeetingGroupPresenter()
        let router = EditMeetingGroupRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }



    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        editView = EditMeetingGroupView(frame: CGRect.zero)
        editView!.delegate = self
        view.addSubview(editView!)
        editView!.heading?.text = "Edit member"
        editView!.translatesAutoresizingMaskIntoConstraints = false
        editView!.leadingAnchor.constraint(equalTo: view.leadingAnchor).isActive = true
        editView!.trailingAnchor.constraint(equalTo: view.trailingAnchor).isActive = true
        editView!.topAnchor.constraint(equalTo: view.topAnchor).isActive = true
        editView!.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
    }

    
    // MARK: - VIP
    
    func populateEditView() {
        let meetingGroup = interactor?.getMeetingGroup()
        editView?.populateFields(meetingGroup: meetingGroup)
    }
    

    func refreshAfterSelectingMembers() {
        let request = EditMeetingGroup.MeetingGroup.Request()
        interactor?.fetchMembers(request: request)
    }
    

    func displayMemberNames(viewModel: EditMeetingGroup.MeetingGroup.ViewModel) {
        editView?.membersDetailLabel?.text = viewModel.memberNames
    }


    // MARK: - EditMeetingGroupViewDelegate methods
    
    func cancelButtonTapped() {
        self.router?.returnToSource(source: self.sourceVC!)
    }
    
    
    func saveButtonTapped(meetingGroup: MeetingGroup) {
        interactor?.saveMeetingGroupToEntity(meetingGroup: meetingGroup, callback: {
            self.router?.returnToSource(source: self.sourceVC!)
        })
    }
    
    
    /*
     Removing a member has its own use-case instead of simply being handled by this interactor.
     Having a separate removal use-case allows the use-case to be used from elsewhere - eg from the master view table.
     */
    func deleteButtonTapped(meetingGroup: MeetingGroup) {
        interactor!.addMeetingGroupToBeDeletedToDataStore(meetingGroup: meetingGroup)
        self.router!.navigateToRemoveMeetingGroup()
    }
    
    
    func membersDisclosureButtonTapped() {
        self.router?.routeToSelectMembers()
    }
}
