//
//  AddSubEntityRouter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 8/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddSubEntityRoutingLogic {
    func returnToSource(source: DisplaySubEntitiesViewController)
    func routeToSelectMembers()
    func returnFromSelectMembers(members: [Member]?)
}

protocol AddSubEntityDataPassing {
    var dataStore: AddSubEntityDataStore? { get }
}


class AddSubEntityRouter: NSObject, AddSubEntityRoutingLogic, AddSubEntityDataPassing {
    weak var viewController: AddSubEntityViewController?
    var dataStore: AddSubEntityDataStore?
    var selectMembersVC: SelectMembersViewController?
    var splitVC: UISplitViewController?
  
    
  // MARK: Routing
  
    func returnToSource(source: DisplaySubEntitiesViewController) {
        var destinationDS = source.router?.dataStore
        passDataToDisplaySubEntitiesDataStore(source: dataStore!, destination: &destinationDS!)
        source.router?.returnFromAddingSubEntity()
    }
    
    
    func routeToSelectMembers() {
        selectMembersVC = SelectMembersViewController(source: viewController!)
        var destinationDS = selectMembersVC?.router?.dataStore
        passDataToSelectMembersDataStore(source: dataStore!, destination: &destinationDS!)
        splitVC = viewController!.splitViewController
        splitVC?.showDetailViewController(selectMembersVC!, sender: viewController)
        selectMembersVC?.fetchMemberNames()
    }
    
    
    func returnFromSelectMembers(members: [Member]?) {
        if members != nil {
            
            viewController!.refreshAfterSelectingMembers()
        }
        splitVC?.showDetailViewController(viewController!, sender: nil)
        selectMembersVC = nil
    }
    
    
    // MARK: Passing data
    
    func passDataToDisplaySubEntitiesDataStore(source: AddSubEntityDataStore, destination: inout DisplaySubEntitiesDataStore) {
        destination.entity = source.entity
    }
    
    
    func passDataToSelectMembersDataStore(source: AddSubEntityDataStore, destination: inout SelectMembersDataStore) {
        destination.entity = source.entity
    }
    
 
}
