//
//  AddSubEntityPresenter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 8/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddSubEntityPresentationLogic {
//    func presentSomething(response: AddSubEntity.Something.Response)
}

class AddSubEntityPresenter: AddSubEntityPresentationLogic {
    weak var viewController: AddSubEntityDisplayLogic?

    // MARK: Do something

//    func presentSomething(response: AddSubEntity.Something.Response) {
//        let viewModel = AddSubEntity.Something.ViewModel()
//        viewController?.displaySomething(viewModel: viewModel)
//    }
}
