//
//  DisplayMeetingGroupsRouter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 8/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DisplayMeetingGroupsRoutingLogic {
    func routeToAddMeetingGroup()
    func routeToEditMeetingGroup()
    func returnFromAddingMeetingGroup()
    func returnFromEditingMeetingGroup()
    func updateDetailVC()
}

protocol DisplayMeetingGroupsDataPassing {
    var dataStore: DisplayMeetingGroupsDataStore? { get }
}

class DisplayMeetingGroupsRouter: NSObject, DisplayMeetingGroupsRoutingLogic, DisplayMeetingGroupsDataPassing {
    weak var viewController: DisplayMeetingGroupsViewController?
    var dataStore: DisplayMeetingGroupsDataStore?
    var addMeetingGroupVC: AddMeetingGroupViewController?
    var displayDetailVC: DisplayDetailViewController?
    var editMeetingGroupVC: EditMeetingGroupViewController?
    
    
    func routeToAddMeetingGroup() {
        addMeetingGroupVC = AddMeetingGroupViewController(sourceVC: viewController!)
        let splitVC = viewController!.splitViewController
        displayDetailVC = splitVC?.viewControllers[1] as? DisplayDetailViewController
        var destinationDS = addMeetingGroupVC?.router?.dataStore
        passDataToAddMeetingGroupDataStore(source: dataStore!, destination: &destinationDS!)
        splitVC?.showDetailViewController(addMeetingGroupVC!, sender: displayDetailVC)
    }
    
    
    func returnFromAddingMeetingGroup() {
        let splitVC = viewController!.splitViewController
        splitVC!.showDetailViewController(displayDetailVC!, sender: nil)
        addMeetingGroupVC = nil
        viewController!.refreshAfterAddingMeetingGroup()
    }
    
    
    
    func updateDetailVC() {
        let splitVC = viewController!.splitViewController
        displayDetailVC = splitVC?.viewControllers[1] as? DisplayDetailViewController
        displayDetailVC?.smallToolbar()
        var destinationDS = displayDetailVC?.router!.dataStore!
        passDataToDisplayDetail(source: dataStore!, destination: &destinationDS!)
        displayDetailVC!.updateDetails()
    }
    
    
    func routeToEditMeetingGroup() {
        editMeetingGroupVC = EditMeetingGroupViewController(sourceVC: viewController!)
        let splitVC = viewController!.splitViewController
        displayDetailVC = splitVC?.viewControllers[1] as? DisplayDetailViewController
        var destinationDS = editMeetingGroupVC?.router?.dataStore
        passDataToEditMeetingGroupDataStore(source: dataStore!, destination: &destinationDS!)
        splitVC?.showDetailViewController(editMeetingGroupVC!, sender: displayDetailVC)
        editMeetingGroupVC!.populateEditView()
    }
    
    
    func returnFromEditingMeetingGroup() {
        let splitVC = viewController!.splitViewController
        splitVC!.showDetailViewController(displayDetailVC!, sender: nil)
        editMeetingGroupVC = nil
        viewController!.refreshAfterEditingMeetingGroup()
    }
    
    
    
    // MARK: Passing data
    
    func passDataToAddMeetingGroupDataStore(source: DisplayMeetingGroupsDataStore, destination: inout AddMeetingGroupDataStore) {
        destination.entity = source.entity
    }
    
    func passDataToEditMeetingGroupDataStore(source: DisplayMeetingGroupsDataStore, destination: inout EditMeetingGroupDataStore) {
        destination.entity = source.entity
        destination.meetingGroup = source.meetingGroup
    }
    
    func passDataToDisplayDetail(source: DisplayMeetingGroupsDataStore, destination: inout DisplayDetailDataStore) {
        destination.selectedItem = source.meetingGroup as AnyObject
    }
}
