//
//  DisplaySubEntitiesPopUpViewController.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 13/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SubEntitiesPopUpViewControllerDelegate: class {
    func didSelectSubEntityInPopUpViewController(_ viewController: DisplaySubEntitiesPopUpViewController, subEntity: SubEntity)
}

protocol DisplaySubEntitiesPopUpDisplayLogic: class {
    func displaySubEntities(viewModel: DisplaySubEntitiesPopUp.SubEntities.ViewModel)
}



class DisplaySubEntitiesPopUpViewController: UIViewController, UITableViewDelegate, UITableViewDataSource, DisplaySubEntitiesPopUpDisplayLogic {
    
    
    var router: (NSObjectProtocol & DisplaySubEntitiesPopUpRoutingLogic & DisplaySubEntitiesPopUpDataPassing)?

    // MARK: Properties
    
    var interactor: DisplaySubEntitiesPopUpBusinessLogic?
    weak var delegate: SubEntitiesPopUpViewControllerDelegate?
    private var theToolbar: UIView?
    private var theTitleLabel: UILabel?
    private var theTableView: UITableView?
    private var subEntityNames: [String]?
    
    // MARK: Constants
    
    private let BUTTON_Y: CGFloat = 27.0
    private let BUTTON_SPACE: CGFloat = 8.0
    private let BUTTON_HEIGHT: CGFloat = 30.0
    private let TITLE_Y: CGFloat = 8.0
    private let TITLE_HEIGHT: CGFloat = 28.0
    private let CANCEL_BUTTON_WIDTH: CGFloat = 56.0
    private let TOOLBAR_HEIGHT: CGFloat = 44.0
    private let MAXIMUM_TABLE_WIDTH: CGFloat = 288.0
    private let MAXIMUM_TABLE_HEIGHT: CGFloat = 464.0
    private let TABLE_CELL_HEIGHT: CGFloat = 42.0
    
    
    
    
    // MARK: Object lifecycle
    
    convenience init(entity: Entity) {
        self.init(nibName: nil, bundle: nil)
        interactor!.setEntity(entity: entity)
    }

    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }


    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    deinit {
        print("DisplaySubEntitiesPopUpViewController deinitialised")
    }

    
    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = DisplaySubEntitiesPopUpInteractor()
        let presenter = DisplaySubEntitiesPopUpPresenter()
        let router = DisplaySubEntitiesPopUpRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

  

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = UIColor(white:0.95, alpha:1.0)
        self.preferredContentSize = CGSize(width: MAXIMUM_TABLE_WIDTH, height: MAXIMUM_TABLE_HEIGHT)
        
        let viewRect = self.view.bounds
        var toolbarRect = viewRect
        toolbarRect.size.height = TOOLBAR_HEIGHT
        toolbarRect.size.width = preferredContentSize.width
        theToolbar = UIView()
        self.view.addSubview(theToolbar!)
        
        /* ------------------------------  Toolbar auto layout --------------------------- */
        theToolbar!.translatesAutoresizingMaskIntoConstraints = false
        theToolbar!.leadingAnchor.constraint(equalTo: view.leadingAnchor).isActive = true
        theToolbar!.topAnchor.constraint(equalTo: view.topAnchor).isActive = true
        theToolbar!.widthAnchor.constraint(equalTo: view.widthAnchor).isActive = true
        theToolbar!.heightAnchor.constraint(equalToConstant: TOOLBAR_HEIGHT).isActive = true
        
        
        let toolbarWidth = theToolbar!.bounds.size.width
        let titleX = BUTTON_SPACE
        let titleWidth = (toolbarWidth - (BUTTON_SPACE + BUTTON_SPACE))
        let titleRect = CGRect(x: titleX, y: TITLE_Y, width: titleWidth, height: TITLE_HEIGHT)
        theTitleLabel = UILabel(frame:titleRect)
        theTitleLabel!.textAlignment = NSTextAlignment.center
        theTitleLabel!.font = UIFont.systemFont(ofSize: 19.0)
        theTitleLabel!.textColor = UIColor(white:0.0, alpha:1.0)
        theTitleLabel!.shadowColor = UIColor(white:0.65, alpha:1.0)
        theTitleLabel!.autoresizingMask = UIViewAutoresizing.flexibleWidth
        theTitleLabel!.backgroundColor = UIColor.clear
        theTitleLabel!.shadowOffset = CGSize(width: 0.0, height: 1.0)
        theTitleLabel!.text = NSLocalizedString("Entities", comment:"title")
        theToolbar!.addSubview(theTitleLabel!)
        
        var tableRect = viewRect
        tableRect.origin.y += TOOLBAR_HEIGHT
        tableRect.size.height -= TOOLBAR_HEIGHT
        theTableView = UITableView(frame:tableRect)
        theTableView!.autoresizingMask = [UIViewAutoresizing.flexibleWidth, UIViewAutoresizing.flexibleHeight]
        theTableView!.dataSource = self
        theTableView!.delegate = self
        theTableView!.rowHeight = TABLE_CELL_HEIGHT
        self.view.addSubview(theTableView!)
        
        fetchSubEntities()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        theTableView!.reloadData()
        theTableView!.contentOffset = CGPoint.zero
    }
    
    override func viewDidAppear(_ animated:Bool) {
        super.viewDidAppear(animated)
        theTableView!.flashScrollIndicators()
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        subEntityNames = [String]()
    }
    
    override func viewDidDisappear(_ animated: Bool) {
        theToolbar = nil
        theTitleLabel = nil
        theTableView = nil
        self.view = nil
        super.viewDidDisappear(animated)
    }
    
    
    // MARK: VIP
    
    func fetchSubEntities() {
        let request = DisplaySubEntitiesPopUp.SubEntities.Request()
        interactor?.fetchSubEntities(request: request)
    }
    
    
    func displaySubEntities(viewModel: DisplaySubEntitiesPopUp.SubEntities.ViewModel) {
        subEntityNames = viewModel.subEntityNames! 
        theTableView!.reloadData()
    }
    
    
//    func reloadData() {
//        subEntityNames = [String]()
//    }
    
    
    // MARK: UITableViewDelegate methods
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        if true {
            let subEntity = interactor!.getSubEntity(index: indexPath.row)
            delegate!.didSelectSubEntityInPopUpViewController(self, subEntity:subEntity)
        }
    }
    
    
    
    // MARK: UITableViewDataSource methods
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        var cell = tableView.dequeueReusableCell(withIdentifier: "popUpSubEntityCell")
        if cell == nil {
            cell = UITableViewCell(style:UITableViewCellStyle.default, reuseIdentifier:"popUpSubEntityCell")
            cell!.textLabel!.font = UIFont.systemFont(ofSize: 17.0)
            cell!.textLabel!.textAlignment = NSTextAlignment.center
            cell!.selectionStyle = UITableViewCellSelectionStyle.gray
        }
        let entityName = subEntityNames![(indexPath).row]
        cell!.textLabel!.text = entityName
        
        return cell!
    }
    
    
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section:Int) -> Int {
        return (subEntityNames!.count)
    }
    
    
}
