//
//  DisplaySubEntitiesPopUpPresenter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 13/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DisplaySubEntitiesPopUpPresentationLogic {
    func presentSubEntities(response: DisplaySubEntitiesPopUp.SubEntities.Response)
}

class DisplaySubEntitiesPopUpPresenter: DisplaySubEntitiesPopUpPresentationLogic {
    weak var viewController: DisplaySubEntitiesPopUpDisplayLogic?

    // MARK: Do something

    func presentSubEntities(response: DisplaySubEntitiesPopUp.SubEntities.Response) {
        var subEntityNames = [String]()
        for subEntity in response.subEntities! {
            subEntityNames.append(subEntity.name!)
        }
        
        let viewModel = DisplaySubEntitiesPopUp.SubEntities.ViewModel(subEntityNames: subEntityNames)
        viewController?.displaySubEntities(viewModel: viewModel)
    }
}
