//
//  AddEventRouter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 15/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddEventRoutingLogic {
   func returnToSource(source: DisplayEventsViewController)
}

protocol AddEventDataPassing {
    var dataStore: AddEventDataStore? { get }
}

class AddEventRouter: NSObject, AddEventRoutingLogic, AddEventDataPassing {
    weak var viewController: AddEventViewController?
    var dataStore: AddEventDataStore?
  
    
  // MARK: Routing
  
    func returnToSource(source: DisplayEventsViewController) {
        source.router?.returnFromAddingEvent()
    }
}
