//
//  ShowHelpPresenter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 28/10/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowHelpPresentationLogic {
    func presentAttributedString(response: ShowHelp.Help.Response)
}

class ShowHelpPresenter: ShowHelpPresentationLogic {
    weak var viewController: ShowHelpDisplayLogic?

    // MARK: Do something

    func presentAttributedString(response: ShowHelp.Help.Response) {
        
        let attString = NSMutableAttributedString()

        var normAtts = HelpAttributes().normal
        normAtts[NSAttributedStringKey.paragraphStyle] = HelpParaStyle().leftWithSpacingBefore
        
        var boldnormAtts = HelpAttributes().normalBold
        boldnormAtts[NSAttributedStringKey.paragraphStyle] = HelpParaStyle().leftWithSpacingBefore
        
        attString.append(NSAttributedString(string: "Remaining list:\n", attributes: boldnormAtts))
        attString.append(NSAttributedString(string: "All members start here, in alphabetical order of last name.\n", attributes: normAtts))
        attString.append(NSAttributedString(string: "Waiting list:\n", attributes: boldnormAtts))
        attString.append(NSAttributedString(string: "Members who have signalled their wish to speak so meeting chair can see who is next to speak.  Members can be re-ordered by pressing the control at the top of the list and moving rows.\n", attributes: normAtts))
        attString.append(NSAttributedString(string: "Speaking list:\n", attributes: boldnormAtts))
        attString.append(NSAttributedString(string: "Members who have spoken and the member currently speaking.\n", attributes: normAtts))
        attString.append(NSAttributedString(string: "How to move members:\n", attributes: boldnormAtts))
        attString.append(NSAttributedString(string: "Either swipe the member name or press the arrow.\n", attributes: normAtts))
        
        
        
        let viewModel = ShowHelp.Help.ViewModel(attString: attString)
        viewController?.displayAttributedString(viewModel: viewModel)
    }
}
