//
//  AddEntityRouter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 1/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddEntityRoutingLogic {
    func returnToSource(source: DisplayEntitiesViewController)
}

protocol AddEntityDataPassing {
    var dataStore: AddEntityDataStore? { get }
}

class AddEntityRouter: NSObject, AddEntityRoutingLogic, AddEntityDataPassing {
    weak var viewController: AddEntityViewController?
    var dataStore: AddEntityDataStore?
  
    
    // MARK: Routing
    
    func returnToSource(source: DisplayEntitiesViewController) {
        source.router?.returnFromAddingEntity() 
    }
}
