//
//  DisplayEventsPopUpPresenter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 15/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DisplayEventsPopUpPresentationLogic {
     func presentEvents(response: DisplayEventsPopUp.Events.Response)
}

class DisplayEventsPopUpPresenter: DisplayEventsPopUpPresentationLogic {
    weak var viewController: DisplayEventsPopUpDisplayLogic?

    // MARK: VIP
    
    func presentEvents(response: DisplayEventsPopUp.Events.Response) {
        var eventNames = [String]()
        for event in response.events! {
            let formatter = DateFormatter()
            formatter.dateFormat = "YYYY-MM-dd"
            let dateString = formatter.string(from: event.date!)
            eventNames.append(dateString)
        }
        
        let viewModel = DisplayEventsPopUp.Events.ViewModel(eventNames: eventNames)
        viewController?.displayEvents(viewModel: viewModel) 
    }
}
