//
//  SelectMembersRouter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 8/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SelectMembersRoutingLogic {
    func returnToSource(members: [Member]?)
}

protocol SelectMembersDataPassing {
    var dataStore: SelectMembersDataStore? { get }
}


class SelectMembersRouter: NSObject, SelectMembersRoutingLogic, SelectMembersDataPassing {
    weak var viewController: SelectMembersViewController?
    var dataStore: SelectMembersDataStore?
  
  
    // MARK: Routing
    
    func returnToSource(members: [Member]?) {
        if members != nil {
            dataStore!.members = members
            var destinationDS = viewController?.source!.router?.dataStore
            passDataToAddSubEntityDataStore(source: dataStore!, destination: &destinationDS! )
        }
        viewController!.source!.router!.returnFromSelectMembers(members: members) 
    }
    
    func passDataToAddSubEntityDataStore(source: SelectMembersDataStore, destination: inout AddSubEntityDataStore ) {
        destination.members = source.members 
    }
}
