//
//  RemoveSubEntityInteractor.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 14/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RemoveSubEntityBusinessLogic {
    func removeSubEntity(callback: @escaping ()->())
}

protocol RemoveSubEntityDataStore {
    var entity: Entity? {get set}
    var subEntity: SubEntity? {get set}
}



class RemoveSubEntityInteractor: RemoveSubEntityBusinessLogic, RemoveSubEntityDataStore {
    var presenter: RemoveSubEntityPresentationLogic?
    var entity: Entity?
    var subEntity: SubEntity?
    

    func removeSubEntity(callback: @escaping ()->()) {
        if subEntity!.id != nil {
            if let idx = entity!.subEntities?.firstIndex(where: {$0.id == subEntity!.id}) {
                entity?.subEntities!.remove(at: idx)
            }
        }
        else {
            if let idx = entity!.subEntities?.firstIndex(where: {$0.name == subEntity!.name}) {
                entity?.subEntities!.remove(at: idx)
            }
        }
        guard let docDirectory = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            print("RemoveSubEntityInteractor: removeSubEntity: error: Document directory not found")
            return
        }
        let docFileURL = docDirectory.appendingPathComponent((entity?.fileName)! + ".ent")
        let entityDoc = EntityDocument(fileURL: docFileURL)
        entityDoc.open(completionHandler: { success in
            if !success {
                print("RemoveSubEntityInteractor: removeSubEntity: error opening EntityDocument")
            }
            else {
                if self.subEntity!.id != nil {
                    if let idx = entityDoc.entity!.subEntities?.firstIndex(where: {$0.id == self.subEntity!.id}) {
                        entityDoc.entity?.subEntities!.remove(at: idx)
                    }
                }
                else {
                    if let idx = entityDoc.entity!.subEntities?.firstIndex(where: {$0.name == self.subEntity!.name}) {
                        entityDoc.entity?.subEntities!.remove(at: idx)
                    }
                }
                entityDoc.updateChangeCount(.done)
                entityDoc.close(completionHandler: { success in
                    print(entityDoc)
                    callback()
                })
            }
        })
    }
}
