//
//  TrackSpeakersPresenter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 14/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TrackSpeakersPresentationLogic {
    func presentSomething(response: TrackSpeakers.Something.Response)
}

class TrackSpeakersPresenter: TrackSpeakersPresentationLogic {
    weak var viewController: TrackSpeakersDisplayLogic?

    // MARK: Do something

    func presentSomething(response: TrackSpeakers.Something.Response) {
        let viewModel = TrackSpeakers.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
