//
//  TrackSpeakersModels.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 14/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TrackSpeakers {
  // MARK: Use cases
  
    enum Speakers {
        struct Request {
        }
        struct Response {
            var baseList: [Member]?
            var speakerList: [Member]?
            var doneList: [Member]?
        }
        struct ViewModel {
            var baseNames: [String]?
            var speakerNames: [String]?
            var doneNames: [String]?
        }
    }
}

struct TablePosition {
    var tableIndex: Int?
    var tableRow: Int?
    init(tableIndex: Int?, tableRow: Int?) {
        self.tableIndex = tableIndex
        self.tableRow = tableRow
    }
}


struct SpeakerRecording {
//    var enabled = false
    var row: Int?
    var button: UIButton?
}

struct UndoStack {
    var speakerMovements: [SpeakerMovement]
}

struct SpeakerMovement {
    var sourceTablePosition: TablePosition?
    var destinationTablePosition: TablePosition?
    var member: Member?
}
