//
//  TrackSpeakersInteractor.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 14/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TrackSpeakersBusinessLogic {
    func doSomething(request: TrackSpeakers.Something.Request)
}

protocol TrackSpeakersDataStore {
  //var name: String { get set }
}

class TrackSpeakersInteractor: TrackSpeakersBusinessLogic, TrackSpeakersDataStore {
    var presenter: TrackSpeakersPresentationLogic?
    var worker: TrackSpeakersWorker?
    //var name: String = ""

    // MARK: Do something

    func doSomething(request: TrackSpeakers.Something.Request) {
        worker = TrackSpeakersWorker()
        worker?.doSomeWork()

        let response = TrackSpeakers.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
