//
//  TrackSpeakersModels.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 14/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TrackSpeakers {
  // MARK: Use cases
  
    enum Speakers {
        struct Request {
        }
        struct Response {
            var remainingList: [Int : [Member]]?
            var waitingList: [Int : [Member]]?
            var speakingList: [Int : [Member]]?
            var currentDebate: Debate?
        }
        struct ViewModel {
            var remainingNames: [Int : [MemberNameWithTime]]?
            var waitingNames: [Int : [MemberNameWithTime]]?
            var speakingNames: [Int : [MemberNameWithTime]]?
        }
    }
}

struct TablePosition {
    var tableIndex: Int?
    var tableSection: Int?
    var tableRow: Int?
    init(tableIndex: Int?, tableSection: Int?, tableRow: Int?) {
        self.tableIndex = tableIndex
        self.tableSection = tableSection
        self.tableRow = tableRow
    }
}

struct MembersTable {
    var tableView: UITableView?
    var nameDictionary: [Int : [MemberNameWithTime]]?
    init(tableView: UITableView?, nameDictionary: [Int : [MemberNameWithTime]]?) {
        self.tableView = tableView
        self.nameDictionary = nameDictionary
    }
}

struct MemberNameWithTime {
    var name: String?
    var time: String?
    init(name: String?, time: String?) {
        self.name = name
        self.time = time
    }
}


struct SpeakerRecording {
    var section: Int?
    var row: Int?
    var button: UIButton?
}

struct UndoStack {
    var speakerMovements: [SpeakerMovement]
}

struct SpeakerMovement {
    var sourceTablePosition: TablePosition?
    var destinationTablePosition: TablePosition?
    var member: Member?
}

struct SectionStatus {
    var isCollapsed = false
    var isAmendment = false
}

enum DebateMode {
    case mainMotion
    case amendment
}
