//
//  TrackSpeakersPresenter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 14/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TrackSpeakersPresentationLogic {
    func presentNames(response: TrackSpeakers.Speakers.Response)
}

class TrackSpeakersPresenter: TrackSpeakersPresentationLogic {
    weak var viewController: TrackSpeakersDisplayLogic?

    // MARK: - VIP

    func presentNames(response: TrackSpeakers.Speakers.Response) {
        var baseNames = [String]()
        var speakerNames = [String]()
        var doneNames = [String]()
        
        for member in response.baseList! {
            let memberName = member.firstName! + " " + member.lastName!
            baseNames.append(memberName)
        }
        for member in response.speakerList! {
            let memberName = member.firstName! + " " + member.lastName!
            speakerNames.append(memberName)
        }
        for member in response.doneList! {
            let memberName = member.firstName! + " " + member.lastName!
            doneNames.append(memberName)
        }
        
        let viewModel = TrackSpeakers.Speakers.ViewModel(baseNames: baseNames, speakerNames: speakerNames, doneNames: doneNames )
        viewController?.displayNames(viewModel: viewModel)
    }
}
