//
//  ShowReportPresenter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 27/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowReportPresentationLogic {
    func presentText(response: ShowReport.Report.Response)
}

class ShowReportPresenter: ShowReportPresentationLogic {
    weak var viewController: ShowReportDisplayLogic?



    func presentText(response: ShowReport.Report.Response) {
        let event = response.event
        let attString = NSMutableAttributedString()
        
        var normAtts = Attributes().normalBase
        normAtts[NSAttributedStringKey.paragraphStyle] = ParaStyle().left
        
        var boldAtts = Attributes().normalBoldBase
        boldAtts[NSAttributedStringKey.paragraphStyle] = ParaStyle().leftWithSpacingBefore
        
        // Entity
        var atts = Attributes().heading1Base
        atts[NSAttributedStringKey.paragraphStyle] = ParaStyle().centered
        let entityAttStrg = NSAttributedString(string: "\n" + ((event?.entity?.name)! + "\n"), attributes: atts)
        attString.append(entityAttStrg)
        
        // Meeting group
        atts = Attributes().heading2Base
        atts[NSAttributedStringKey.paragraphStyle] = ParaStyle().centeredWithSpacingBeforeAfter
        let meetingGroupAttStrg = NSAttributedString(string: (event?.meetingGroup?.name)! + "\n", attributes: atts)
        attString.append(meetingGroupAttStrg)
        
        // Date
        let formatter = DateFormatter()
        formatter.dateStyle = .long
        formatter.timeStyle = .none
        let dateStrg = formatter.string(from: (event?.date)!)
        formatter.dateStyle = .none
        formatter.timeStyle = .short
        let timeStrg = formatter.string(from: (event?.date)!)
        atts = Attributes().heading3Base
        atts[NSAttributedStringKey.paragraphStyle] = ParaStyle().centered
        let dateAttStrg = NSAttributedString(string: timeStrg + "\n" + dateStrg + "\n", attributes: atts)
        attString.append(dateAttStrg)
        
        // Members

        attString.append(NSAttributedString(string:  "\nMembers:\n", attributes: boldAtts))
        
        var membersStg = String()
        for member in (event?.meetingGroup?.members)! {
            if membersStg.count > 0 {
                membersStg.append(", ")
            }
            let fullName = member.title! + " " + member.firstName! +  " " + member.lastName!
            membersStg.append(fullName)
        }
        let membersAttStrg = NSAttributedString(string: membersStg + "\n", attributes: normAtts)
        attString.append(membersAttStrg)
        
        // Debates
        atts = Attributes().normalBase
        atts[NSAttributedStringKey.paragraphStyle] = ParaStyle().left
        attString.append(NSAttributedString(string: "Debates:\n", attributes: boldAtts))
        if event?.debates != nil {
            for debate in (event?.debates)! {
                let refAttStg = NSAttributedString(string: debate.reference! + "\n", attributes: boldAtts)
                attString.append(refAttStg)
                var spkrEvtStrg = String()
                for speakerEvt in debate.speakerEvents! {
                    let lastNm = speakerEvt.member?.lastName
                    let spkgTime = speakerEvt.elapsedSeconds
                    spkrEvtStrg.append(lastNm! + "\t" + String(spkgTime!) + "\n")
                }

                let spkrEvtAttStr = NSAttributedString(string: spkrEvtStrg, attributes: normAtts)
                attString.append(spkrEvtAttStr)
            }
        }
        
        attString.fixAttributes(in: NSRange(location: 0, length: attString.length))
        
        let viewModel = ShowReport.Report.ViewModel(attText: attString)
        viewController?.displayText(viewModel: viewModel)
    }
}
