//
//  ShowReportInteractor.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 27/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowReportBusinessLogic {
    func fetchText(request: ShowReport.Report.Request)
    func setAttText(attText: NSAttributedString)
    func getPdfUrl()-> URL
    func removePdf()
}

protocol ShowReportDataStore {
    var selectedItem: Event? {get set}
    var attText: NSAttributedString? {get set}
    var pdfUrl: URL? {get set}
}


class ShowReportInteractor: ShowReportBusinessLogic, ShowReportDataStore {
    var presenter: ShowReportPresentationLogic?
    var selectedItem: Event?
    var attText: NSAttributedString?
    var pdfUrl: URL?
    
    
    // MARK: - VIP

    func fetchText(request: ShowReport.Report.Request) {
        let response = ShowReport.Report.Response(event: selectedItem)
        presenter?.presentText(response: response)
    }
    
    // MARK: - Datastore
    
    func setAttText(attText: NSAttributedString) {
        self.attText = attText
    }
    
    func getPdfUrl()-> URL {
        return pdfUrl!
    }
    
    
    func removePdf() {        
        do {
            try FileManager.default.removeItem(at: pdfUrl!)
        } catch {
            print(error)
        }
    }
    
}
