//
//  ShowReportPresenter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 27/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowReportPresentationLogic {
    func presentText(response: ShowReport.Report.Response)
}

class ShowReportPresenter: ShowReportPresentationLogic {
    weak var viewController: ShowReportDisplayLogic?



    func presentText(response: ShowReport.Report.Response) {
        let event = response.event
        let attString = NSMutableAttributedString()
        
        var normAtts = Attributes().normalBase
        normAtts[NSAttributedString.Key.paragraphStyle] = ParaStyle().left
        
        var boldAtts = Attributes().normalBoldBase
        boldAtts[NSAttributedString.Key.paragraphStyle] = ParaStyle().leftWithSpacingBefore
        
        var italicAtts = Attributes().normalItalicBase
        italicAtts[NSAttributedString.Key.paragraphStyle] = ParaStyle().leftWithSpacingAfter
        
        
        // Entity
        var atts = Attributes().heading1Base
        atts[NSAttributedString.Key.paragraphStyle] = ParaStyle().centered
        let entityAttStrg = NSAttributedString(string: "\n" + ((event?.entity?.name)! + "\n"), attributes: atts)
        attString.append(entityAttStrg)
        
        // Meeting group
        atts = Attributes().heading2Base
        atts[NSAttributedString.Key.paragraphStyle] = ParaStyle().centeredWithSpacingBeforeAfter
        let meetingGroupAttStrg = NSAttributedString(string: (event?.meetingGroup?.name)! + "\n", attributes: atts)
        attString.append(meetingGroupAttStrg)
        
        // Date
        let formatter = DateFormatter()
        formatter.dateStyle = .long
        formatter.timeStyle = .none
        let dateStrg = formatter.string(from: (event?.date)!)
        formatter.dateStyle = .none
        formatter.timeStyle = .short
        let timeStrg = formatter.string(from: (event?.date)!)
        atts = Attributes().heading3Base
        atts[NSAttributedString.Key.paragraphStyle] = ParaStyle().centered
        let dateAttStrg = NSAttributedString(string: timeStrg + ", " + dateStrg + "\n", attributes: atts)
        attString.append(dateAttStrg)
        
        // Members

        attString.append(NSAttributedString(string:  "Members:\n", attributes: boldAtts))
        var meetingGroupMembers = [Member]()
        for memberID in event!.meetingGroup!.memberIDs! {
            let mmbr = event!.entity!.members!.first(where: {$0.id == memberID })
            meetingGroupMembers.append(mmbr!)
        }
        var membersStg = String()
        for member in meetingGroupMembers {
            if membersStg.count > 0 {
                membersStg.append(", ")
            }
            let fullName = member.title! + " " + member.firstName! +  " " + member.lastName!
            membersStg.append(fullName)
        }
        let membersAttStrg = NSAttributedString(string: membersStg + "\n\n", attributes: normAtts)
        attString.append(membersAttStrg)
        
        attString.append(NSAttributedString(string:  "\tDuration\tStart-time\n", attributes: boldAtts))
        
        
        // Debates
        atts = Attributes().normalBase
        atts[NSAttributedString.Key.paragraphStyle] = ParaStyle().left
        if event?.debates != nil {
            for debate in (event?.debates)! {
                (boldAtts[NSAttributedString.Key.paragraphStyle] as! NSMutableParagraphStyle).firstLineHeadIndent = 0
                let debateNumberAttStg = NSAttributedString(string: "\nDebate " +  String(debate.debateNumber!) + "\n", attributes: boldAtts)
                attString.append(debateNumberAttStg)
                if let note = debate.note {
                    let refAttStg = NSAttributedString(string: note + "\n", attributes: italicAtts)
                    attString.append(refAttStg)
                }
                for debateSection in debate.debateSections! {
                    var debateSectionNameAtts = Attributes().normalBoldBase
                    debateSectionNameAtts[NSAttributedString.Key.paragraphStyle] = ParaStyle().leftWithSpacingBefore
                    (debateSectionNameAtts[NSAttributedString.Key.paragraphStyle] as! NSMutableParagraphStyle).firstLineHeadIndent = 20
                    let debateSectionNameAttStg = NSAttributedString(string: debateSection.sectionName! + "\n", attributes: debateSectionNameAtts)
                    attString.append(debateSectionNameAttStg)
                    var spkrEvtStrg = String()
                    for speakerEvt in debateSection.speakerEvents! { 
                        let fullName = speakerEvt.member!.title! + " " + speakerEvt.member!.firstName! +  " " +  speakerEvt.member!.lastName!
                        let spkgTime = String(format: "%02d:%02d", speakerEvt.elapsedMinutes!, speakerEvt.elapsedSeconds!)
                        formatter.dateStyle = .none
                        formatter.timeStyle = .short
                        let startTime = formatter.string(from: (speakerEvt.startTime)!)
                        spkrEvtStrg.append(fullName + "\t" + String(spkgTime) + "\t" + startTime + "\n")
                    }
                    var spkrAtts = Attributes().normalBase
                    spkrAtts[NSAttributedString.Key.paragraphStyle] = ParaStyle().left
                    (spkrAtts[NSAttributedString.Key.paragraphStyle] as! NSMutableParagraphStyle).firstLineHeadIndent = 20
                    let spkrEvtAttStr = NSAttributedString(string: spkrEvtStrg, attributes: spkrAtts)
                    attString.append(spkrEvtAttStr)
                }
            }
        }
        
        attString.fixAttributes(in: NSRange(location: 0, length: attString.length))
        print(attString)
        
        let viewModel = ShowReport.Report.ViewModel(attText: attString)
        viewController?.displayText(viewModel: viewModel)
    }
}
