//
//  EditMemberPresenter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 9/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditMemberPresentationLogic {
//    func presentSomething(response: EditMember.Something.Response)
}

class EditMemberPresenter: EditMemberPresentationLogic {
    weak var viewController: EditMemberDisplayLogic?

    // MARK: Do something


}
