//
//  DisplayEntitiesPopUpPresenter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 7/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DisplayEntitiesPopUpPresentationLogic {
    func presentEntities(response: DisplayEntitiesPopUp.Entities.Response) 
}

class DisplayEntitiesPopUpPresenter: DisplayEntitiesPopUpPresentationLogic {
    weak var viewController: DisplayEntitiesPopUpDisplayLogic?

    // MARK: Do something

    func presentEntities(response: DisplayEntitiesPopUp.Entities.Response) {
        var entityNames = [String]()
        for entity in response.entities! {
            entityNames.append(entity.name!)
        }
        
        let viewModel = DisplayEntitiesPopUp.Entities.ViewModel(entityNames:entityNames)
        viewController?.displayEntities(viewModel: viewModel)
    }
}
