//
//  DisplayMeetingGroupsPopUpViewController.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 13/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MeetingGroupsPopUpViewControllerDelegate: class {
    func didSelectMeetingGroupInPopUpViewController(_ viewController: DisplayMeetingGroupsPopUpViewController, meetingGroup: MeetingGroup)
    func didSelectDeletedGroupsInPopUpViewController()
}

protocol DisplayMeetingGroupsPopUpDisplayLogic: class {
    func displayMeetingGroups(viewModel: DisplayMeetingGroupsPopUp.MeetingGroups.ViewModel)
}



class  DisplayMeetingGroupsPopUpViewController: UIViewController, UITableViewDelegate, UITableViewDataSource, DisplayMeetingGroupsPopUpDisplayLogic {
    
    
//    var router: (NSObjectProtocol &  DisplayMeetingGroupsPopUpDataPassing)?

    // MARK: Properties
    
    var interactor:  DisplayMeetingGroupsPopUpBusinessLogic?
    weak var delegate: MeetingGroupsPopUpViewControllerDelegate?
    private var theToolbar: UIView?
    private var theTitleLabel: UILabel?
    private var theTableView: UITableView?
    private var meetingGroupNames: [String]?
    
    // MARK: Constants
    
    private let BUTTON_Y: CGFloat = 27.0
    private let BUTTON_SPACE: CGFloat = 8.0
    private let BUTTON_HEIGHT: CGFloat = 30.0
    private let TITLE_Y: CGFloat = 8.0
    private let TITLE_HEIGHT: CGFloat = 28.0
    private let CANCEL_BUTTON_WIDTH: CGFloat = 56.0
    private let TOOLBAR_HEIGHT: CGFloat = 44.0
    private let MAXIMUM_TABLE_WIDTH: CGFloat = 288.0
    private let MAXIMUM_TABLE_HEIGHT: CGFloat = 464.0
    private let TABLE_CELL_HEIGHT: CGFloat = 42.0
    
    
    
    
    // MARK: Object lifecycle
    
    convenience init(entity: Entity, includeDeletedGroups: Bool?) {
        self.init(nibName: nil, bundle: nil)
        if includeDeletedGroups != nil {
            interactor!.setIncludeDeletedGroups(includeDeletedGroups: includeDeletedGroups!)
        }
        interactor!.setEntity(entity: entity)
    }

    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }


    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    deinit {
        print(" DisplayMeetingGroupsPopUpViewController deinitialised")
    }

    
    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor =  DisplayMeetingGroupsPopUpInteractor()
        let presenter = DisplayMeetingGroupsPopUpPresenter()
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController
    }

  

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = UIColor(white:0.95, alpha:1.0)
        self.preferredContentSize = CGSize(width: MAXIMUM_TABLE_WIDTH, height: MAXIMUM_TABLE_HEIGHT)
        
        let viewRect = self.view.bounds
        var toolbarRect = viewRect
        toolbarRect.size.height = TOOLBAR_HEIGHT
        toolbarRect.size.width = preferredContentSize.width
        theToolbar = UIView()
        self.view.addSubview(theToolbar!)
        
        /* ------------------------------  Toolbar auto layout --------------------------- */
        theToolbar!.translatesAutoresizingMaskIntoConstraints = false
        theToolbar!.leadingAnchor.constraint(equalTo: view.leadingAnchor).isActive = true
        theToolbar!.topAnchor.constraint(equalTo: view.topAnchor).isActive = true
        theToolbar!.widthAnchor.constraint(equalTo: view.widthAnchor).isActive = true
        theToolbar!.heightAnchor.constraint(equalToConstant: TOOLBAR_HEIGHT).isActive = true
        
        
        let toolbarWidth = theToolbar!.bounds.size.width
        let titleX = BUTTON_SPACE
        let titleWidth = (toolbarWidth - (BUTTON_SPACE + BUTTON_SPACE))
        let titleRect = CGRect(x: titleX, y: TITLE_Y, width: titleWidth, height: TITLE_HEIGHT)
        theTitleLabel = UILabel(frame:titleRect)
        theTitleLabel!.textAlignment = NSTextAlignment.center
        theTitleLabel!.font = UIFont.systemFont(ofSize: 19.0)
        theTitleLabel!.textColor = UIColor(white:0.0, alpha:1.0)
        theTitleLabel!.shadowColor = UIColor(white:0.65, alpha:1.0)
        theTitleLabel!.autoresizingMask = UIView.AutoresizingMask.flexibleWidth
        theTitleLabel!.backgroundColor = UIColor.clear
        theTitleLabel!.shadowOffset = CGSize(width: 0.0, height: 1.0)
        theTitleLabel!.text = NSLocalizedString("Meeting groups", comment:"title")
        theToolbar!.addSubview(theTitleLabel!)
        
        var tableRect = viewRect
        tableRect.origin.y += TOOLBAR_HEIGHT
        tableRect.size.height -= TOOLBAR_HEIGHT
        theTableView = UITableView(frame:tableRect)
        theTableView!.autoresizingMask = [UIView.AutoresizingMask.flexibleWidth, UIView.AutoresizingMask.flexibleHeight]
        theTableView!.dataSource = self
        theTableView!.delegate = self
        theTableView!.rowHeight = TABLE_CELL_HEIGHT
        self.view.addSubview(theTableView!)
        
        fetchMeetingGroups()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        theTableView!.reloadData()
        theTableView!.contentOffset = CGPoint.zero
    }
    
    override func viewDidAppear(_ animated:Bool) {
        super.viewDidAppear(animated)
        theTableView!.flashScrollIndicators()
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        meetingGroupNames = [String]()
    }
    
    override func viewDidDisappear(_ animated: Bool) {
        theToolbar = nil
        theTitleLabel = nil
        theTableView = nil
        self.view = nil
        super.viewDidDisappear(animated)
    }
    
    
    // MARK: VIP
    
    private func fetchMeetingGroups() {
        let request = DisplayMeetingGroupsPopUp.MeetingGroups.Request()
        interactor?.fetchMeetingGroups(request: request)
    }
    
    
    func displayMeetingGroups(viewModel: DisplayMeetingGroupsPopUp.MeetingGroups.ViewModel) {
        meetingGroupNames = viewModel.meetingGroupNames!
        theTableView!.reloadData()
    }
    
    
    // MARK: Methods
    
    func reloadData() {
        meetingGroupNames = [String]()
    }
    
    
    // MARK: UITableViewDelegate methods
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let selectedCell = tableView.cellForRow(at: indexPath)
        if selectedCell?.textLabel?.text == "Deleted groups" {
            delegate?.didSelectDeletedGroupsInPopUpViewController()
        }
        else {
            var idx = indexPath.row
            let firstCell = tableView.cellForRow(at: IndexPath(row: 0, section: 0))
            if firstCell?.textLabel!.text == "Deleted groups" { idx -= 1}
            let meetingGroup = interactor!.getMeetingGroup(index: idx)
            delegate!.didSelectMeetingGroupInPopUpViewController(self, meetingGroup:meetingGroup)
        }
    }
    
    
    
    // MARK: UITableViewDataSource methods
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        var cell = tableView.dequeueReusableCell(withIdentifier: "popUpMeetingGroupCell")
        if cell == nil {
            cell = UITableViewCell(style:UITableViewCell.CellStyle.default, reuseIdentifier:"popUpMeetingGroupCell")
            cell!.textLabel!.font = UIFont.systemFont(ofSize: 17.0)
            cell!.textLabel!.textAlignment = NSTextAlignment.center
            cell!.selectionStyle = UITableViewCell.SelectionStyle.gray
        }
        if meetingGroupNames!.count == 0 {
            cell!.textLabel!.textColor = UIColor.lightGray
            cell!.textLabel!.text = "Create a meeting group in Setup"
            cell?.isUserInteractionEnabled = false
        }
        else {
            let meetingGroupName = meetingGroupNames![(indexPath).row]
            cell!.textLabel!.textColor = UIColor.black
            cell!.textLabel!.text = meetingGroupName
            cell?.isUserInteractionEnabled = true
        }

        
        return cell!
    }
    
    
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section:Int) -> Int {
        if meetingGroupNames!.count == 0 {
            return 1
        }
        return (meetingGroupNames!.count)
    }
    
    
}
