//
//  DisplayMeetingGroupsPopUpPresenter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 13/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol  DisplayMeetingGroupsPopUpPresentationLogic {
    func presentMeetingGroups(response:  DisplayMeetingGroupsPopUp.MeetingGroups.Response)
}


class DisplayMeetingGroupsPopUpPresenter:  DisplayMeetingGroupsPopUpPresentationLogic {
    weak var viewController: DisplayMeetingGroupsPopUpDisplayLogic?

    func presentMeetingGroups(response:  DisplayMeetingGroupsPopUp.MeetingGroups.Response) {
        var meetingGroupNames = [String]()
        if response.includePreviousGroups != nil && response.includePreviousGroups! == true {
            meetingGroupNames.append("Deleted groups")
        }
        for meetingGroup in response.meetingGroups! {
            meetingGroupNames.append(meetingGroup.name!)
        }
        
        let viewModel = DisplayMeetingGroupsPopUp.MeetingGroups.ViewModel(meetingGroupNames: meetingGroupNames)
        viewController?.displayMeetingGroups(viewModel: viewModel)
    }
}
