//
//  DisplayEntitiesPopUpInteractor.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 7/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DisplayEntitiesPopUpBusinessLogic {
   func fetchEntities(request: DisplayEntitiesPopUp.Entities.Request)
}

protocol DisplayEntitiesPopUpDataStore {
    //var name: String { get set }
}


class DisplayEntitiesPopUpInteractor: DisplayEntitiesPopUpBusinessLogic, DisplayEntitiesPopUpDataStore {
    var presenter: DisplayEntitiesPopUpPresenter?
    var entity: Entity?
    var entities: [Entity]?
    
    
    
    func fetchEntities(request: DisplayEntitiesPopUp.Entities.Request) {
        entities = [Entity]()
        let fileManager = FileManager.default
        guard let docDirectory = fileManager.urls(for: .documentDirectory, in: .userDomainMask).first else {
            print("DisplayEntitiesPopUpInteractorInteractor: fetchEntities: error: Document directory not found")
            return
        }
        do {
            let fileURLs = try fileManager.contentsOfDirectory(at: docDirectory, includingPropertiesForKeys: nil)
            for url in fileURLs {
                if url.pathExtension == "ent" {
                    let entityDoc = EntityDocument(fileURL: url)
                    entityDoc.open(completionHandler: { success in
                        if !success {
                            print("DisplayEntitiesPopUpInteractorInteractor: fetchEntities: error opening EntityDocument")
                        }
                        else {
                            entityDoc.close(completionHandler: { success in
                                guard var entity = entityDoc.entity else {
                                    print("DisplayEntitiesPopUpInteractorInteractor: fetchEntities: entity is nil")
                                    return
                                }
                                if entity.fileName == nil {
                                    let urlWithoutExt = url.deletingPathExtension()
                                    entity.fileName = urlWithoutExt.lastPathComponent
                                }
                                self.entities!.append(entity)
                                let response = DisplayEntitiesPopUp.Entities.Response(entities: self.entities)
                                self.presenter?.presentEntities(response: response) 
                            })
                        }
                    })
                }
            }
            
        } catch {
            print("DisplayEntitiesPopUpInteractorInteractor: error while enumerating files \(docDirectory.path): \(error.localizedDescription)")
        }
    }
    
    
    func getEntity(index: Int) -> Entity {
        return entities![index]
    }
}
