//
//  DisplaySubEntitiesModels.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 8/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DisplayMeetingGroups {
  // MARK: Use cases
  
  enum MeetingGroups {
    struct Request {
        var entity: Entity?
    }
    struct Response {
        var meetingGroups: [MeetingGroup]?
    }
    struct ViewModel {
        var meetingGroupNames: [String]?
    }
  }
}
