//
//  ConvertToPdfRouter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 28/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ConvertToPdfRoutingLogic {
   func returnToSourceRouter()
}

protocol ConvertToPdfDataPassing {
    var dataStore: ConvertToPdfDataStore? { get }
}

class ConvertToPdfRouter: NSObject, ConvertToPdfRoutingLogic, ConvertToPdfDataPassing {
    weak var controller: ConvertToPdfController?
    var dataStore: ConvertToPdfDataStore?
  
  // MARK: Routing
  
    func returnToSourceRouter() {
        let destination = controller?.sourceRouter
        var destinationDS = destination!.dataStore!
        passDataToShowReport(source: dataStore!, destination: &destinationDS)
        controller!.sourceRouter!.returnFromConvertToPdf()
    }
    

  // MARK: Passing data
  
    func passDataToShowReport(source: ConvertToPdfDataStore, destination: inout ShowReportDataStore) {
        destination.pdfUrl = source.pdfUrl
    }
}
