//
//  RemoveMeetingGroupInteractor.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 14/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RemoveMeetingGroupBusinessLogic {
    func removeMeetingGroup(callback: @escaping ()->())
}

protocol RemoveMeetingGroupDataStore {
    var entity: Entity? {get set}
    var meetingGroup: MeetingGroup? {get set}
}



class RemoveMeetingGroupInteractor: RemoveMeetingGroupBusinessLogic, RemoveMeetingGroupDataStore {
    var entity: Entity?
    var meetingGroup: MeetingGroup?
    
    /*
     For the entity, remove the meeting group with same meetingGroup.id, or, if that is not available, with same meetingGroup.name
     If the current entity saved in defaults is this entity, replace it with this updated one (which has the meeting group removed).
     Open the entity document and update its entity property with this one.
     */
    func removeMeetingGroup(callback: @escaping ()->()) {
        if meetingGroup!.id != nil {
            if let idx = entity!.meetingGroups?.firstIndex(where: {$0.id == meetingGroup!.id}) {
                entity?.meetingGroups!.remove(at: idx)
            }
        }
        else {
            if let idx = entity!.meetingGroups?.firstIndex(where: {$0.name == meetingGroup!.name}) {
                entity?.meetingGroups!.remove(at: idx)
            }
        }
        let savedEntity = UserDefaultsManager.getCurrentEntity()
        if savedEntity == self.entity {
            UserDefaultsManager.saveCurrentEntity(entity: self.entity!)
        }
        guard let docDirectory = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            print("RemoveMeetingGroupInteractor: removeMeetingGroup: error: Document directory not found")
            return
        }
        let docFileURL = docDirectory.appendingPathComponent((entity?.id?.uuidString)! + ".ent")
        let entityDoc = EntityDocument(fileURL: docFileURL)
        entityDoc.open(completionHandler: { success in
            if !success {
                print("RemoveMeetingGroupInteractor: removeMeetingGroup: error opening EntityDocument")
            }
            else {
                if self.meetingGroup!.id != nil {
                    if let idx = entityDoc.entity!.meetingGroups?.firstIndex(where: {$0.id == self.meetingGroup!.id}) {
                        entityDoc.entity?.meetingGroups!.remove(at: idx)
                    }
                }
                else {
                    if let idx = entityDoc.entity!.meetingGroups?.firstIndex(where: {$0.name == self.meetingGroup!.name}) {
                        entityDoc.entity?.meetingGroups!.remove(at: idx)
                    }
                }
                entityDoc.updateChangeCount(.done)
                entityDoc.close(completionHandler: { success in
                    print(entityDoc)
                    self.changeMeetingGroupStatusInEvents(callback: {
                        self.meetingGroup = nil
                        callback()
                    })
                })
            }
        })
    }
    
    
    func changeMeetingGroupStatusInEvents(callback:@escaping ()->()) {
        let fileManager = FileManager.default
        guard let docDirectory = fileManager.urls(for: .documentDirectory, in: .userDomainMask).first else {
            print("RemoveMeetingGroupInteractor: changeMeetingGroupStatusInEvents: error: Document directory not found")
            return
        }
        do {
            var eventUrls = [URL]()
            let fileURLs = try fileManager.contentsOfDirectory(at: docDirectory, includingPropertiesForKeys: nil)
            for url in fileURLs {
                if url.pathExtension == "evt" {
                    eventUrls.append(url)
                }
            }
            if eventUrls.count > 0 {
                var count = 0
                for eventUrl in eventUrls {
                    let eventDoc = EventDocument(fileURL: eventUrl)
                    eventDoc.open(completionHandler: { success in
                        if !success {
                            print("RemoveMeetingGroupInteractor: changeMeetingGroupStatusInEvents: error opening EventDocument")
                            return
                        }
                        else {
                            guard var event = eventDoc.event else {
                                print("RemoveMeetingGroupInteractor: changeMeetingGroupStatusInEvents: event is nil")
                                return
                            }
                            if event.meetingGroup == self.meetingGroup {
                                event.meetingGroupStatus = .previous
                                eventDoc.event = event
                                eventDoc.updateChangeCount(.done)
                            }
                            
                            eventDoc.close(completionHandler: {success in
                                count += 1
                                if count == eventUrls.count {
									callback()
                                }
                            })
                        }
                    })
                }
            }
        }
        catch {
            print("Error while enumerating files \(docDirectory.path): \(error.localizedDescription)")
        }
    }
    
    
}
