//
//  EditEntityPresenter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 1/10/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditEntityPresentationLogic {
//    func presentSomething(response: EditEntity.Something.Response)
}

class EditEntityPresenter: EditEntityPresentationLogic {
    weak var viewController: EditEntityDisplayLogic?

    // MARK: Do something

//    func presentSomething(response: EditEntity.Something.Response) {
//        let viewModel = EditEntity.Something.ViewModel()
//        viewController?.displaySomething(viewModel: viewModel)
//    }
}
