//
//  DisplayEventsRouter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 2/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DisplayEventsRoutingLogic {
    func routeToAddEvent()
    func returnFromAddingEvent()
    func routeToEditEvent()
    func returnFromEditingEvent()
    func updateDetailVC()
}

protocol DisplayEventsDataPassing {
    var dataStore: DisplayEventsDataStore? { get }
}

class DisplayEventsRouter: NSObject, DisplayEventsRoutingLogic, DisplayEventsDataPassing {
    weak var viewController: DisplayEventsViewController?
    var dataStore: DisplayEventsDataStore?
    var addEventVC: AddEventViewController?
    var editEventVC: EditEventViewController?
    var displayDetailVC: DisplayDetailViewController?
    var displayNavC: UINavigationController?
  
    
  // MARK: Routing
  
    func routeToAddEvent() {
        addEventVC = AddEventViewController(sourceVC: viewController!)
        let splitVC = viewController!.splitViewController
        displayNavC = splitVC?.viewControllers[1] as? UINavigationController
        var destinationDS = addEventVC?.router!.dataStore!
        passDataToAddEvent(source: dataStore!, destination: &destinationDS!)
        displayNavC?.pushViewController(addEventVC!, animated: true)
    }
    
    
    func returnFromAddingEvent() {
        displayNavC?.popViewController(animated: true)
        addEventVC = nil
        viewController?.fetchEvents()
    }
    
    
    func routeToEditEvent() {
        editEventVC = EditEventViewController(sourceVC: viewController!)
        let splitVC = viewController!.splitViewController
        displayNavC = splitVC?.viewControllers[1] as? UINavigationController
        var destinationDS = editEventVC?.router!.dataStore!
        passDataToEditEvent(source: dataStore!, destination: &destinationDS!)
        displayNavC?.pushViewController(editEventVC!, animated: true)
    }
    
    
    func returnFromEditingEvent() {
        displayNavC?.popViewController(animated: true)
        editEventVC = nil
        viewController?.fetchEvents()
    }
    
    func updateDetailVC() {
        let splitVC = viewController!.splitViewController
        displayNavC = splitVC?.viewControllers[1] as? UINavigationController
        displayDetailVC = displayNavC?.viewControllers[0] as? DisplayDetailViewController
        var destinationDS = displayDetailVC?.router!.dataStore!
        passDataToDisplayDetail(source: dataStore!, destination: &destinationDS!)
        displayDetailVC!.updateDetails()
    }
    
    
    func passDataToDisplayDetail(source: DisplayEventsDataStore, destination: inout DisplayDetailDataStore) {
        destination.selectedItem = source.event as AnyObject
    }
    
    func passDataToAddEvent(source: DisplayEventsDataStore, destination: inout AddEventDataStore) {
        destination.entity = source.entity
        destination.meetingGroup = source.meetingGroup
    }
    
    func passDataToEditEvent(source: DisplayEventsDataStore, destination: inout EditEventDataStore) {
        destination.event = source.event
    }
}
