//
//  RemoveEventController.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 14/10/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RemoveEventDisplayLogic: class {

}



class RemoveEventController: NSObject, RemoveEventDisplayLogic {
    var interactor: RemoveEventBusinessLogic?
    var router: (NSObjectProtocol & RemoveEventRoutingLogic & RemoveEventDataPassing)?
    var sourceVC: EditEventViewController?

    
    // MARK: Object lifecycle
    
    convenience init(source: EditEventViewController) {
        self.init()
        self.sourceVC = source
        setup()
    }
    
    
    override init() {
        super.init()
    }
    
    
    deinit {
        print("RemoveEventController: deinitialising")
    }


    // MARK: Setup

    private func setup() {
        let controller = self
        let interactor = RemoveEventInteractor()
        let presenter = RemoveEventPresenter()
        let router = RemoveEventRouter()
        controller.interactor = interactor
        controller.router = router
        interactor.presenter = presenter
        presenter.controller = controller
        router.controller = controller
        router.dataStore = interactor
    }


  func removeEvent() {
        interactor?.removeEvent(callback: { 
            self.router!.returnToSource(source: self.sourceVC!)
        })
    }
}
