//
//  RemoveEventInteractor.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 14/10/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RemoveEventBusinessLogic {
    func removeEvent(callback: @escaping ()->())
}

protocol RemoveEventDataStore {
    var event: Event? {get set}
}

class RemoveEventInteractor: RemoveEventBusinessLogic, RemoveEventDataStore {
    var presenter: RemoveEventPresentationLogic?
    var event: Event?

    
    
    func removeEvent(callback: @escaping ()->()) {

        guard let docDirectory = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            print("RemoveEventInteractor: removeEvent: error: Document directory not found")
            return
        }
        let docFileURL = docDirectory.appendingPathComponent((event?.filename)! + ".evt")
        do {
            try FileManager.default.removeItem(at: docFileURL)
            callback()
        }
        catch {
            print(error)
        }
    }
}
