//
//  RemoveEventRouter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 14/10/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RemoveEventRoutingLogic {
    func returnToSource(source: EditEventViewController)
}

protocol RemoveEventDataPassing {
    var dataStore: RemoveEventDataStore? { get }
}

class RemoveEventRouter: NSObject, RemoveEventRoutingLogic, RemoveEventDataPassing {
    weak var controller: RemoveEventController?
    var dataStore: RemoveEventDataStore?
  
    // MARK: Routing
    
    func returnToSource(source: EditEventViewController) {
        var destinationDS = source.router?.dataStore
        passDataToEditEventDataStore(source: dataStore!, destination: &destinationDS!)
        source.router!.returnFromRemovingEvent()  
    }
    
    
    // MARK: Passing data
    
    func passDataToEditEventDataStore(source: RemoveEventDataStore, destination: inout EditEventDataStore) {
        destination.event = source.event
    }
  

}
