//
//  AddMemberRouter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 2/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddMemberRoutingLogic {
    func returnToSource(source: DisplayMembersViewController)
}

protocol AddMemberDataPassing {
    var dataStore: AddMemberDataStore? { get }
}

class AddMemberRouter: NSObject, AddMemberRoutingLogic, AddMemberDataPassing {
    weak var viewController: AddMemberViewController?
    var dataStore: AddMemberDataStore?
  
  
    // MARK: Routing
    
    func returnToSource(source: DisplayMembersViewController) {
        var destinationDS = source.router?.dataStore
        passDataToDisplayMemberDataStore(source: dataStore!, destination: &destinationDS!)
        source.router?.returnFromAddingMember()
    }
  
  
  
  // MARK: Passing data
  
  func passDataToDisplayMemberDataStore(source: AddMemberDataStore, destination: inout DisplayMembersDataStore) {
    destination.entity = source.entity
  }
}
