//
//  AddMemberInteractor.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 2/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddMemberBusinessLogic {
    func saveMemberToEntity(member: Member, callback: @escaping ()->())
}

protocol AddMemberDataStore {
    var entity: Entity? { get set }
}

class AddMemberInteractor: AddMemberBusinessLogic, AddMemberDataStore {
    var presenter: AddMemberPresentationLogic?
    var entity: Entity?


    // MARK: VIP
    func saveMemberToEntity(member: Member, callback: @escaping ()->()) {
        if entity!.members == nil {
            entity!.members = [Member]()
        }
        entity?.members?.append(member)
        guard let docDirectory = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            print("DisplayMembersInteractor: fetchMembers: error: Document directory not found")
            return
        }
        let docFileURL = docDirectory.appendingPathComponent((entity?.fileName)! + ".ent")
        let entityDoc = EntityDocument(fileURL: docFileURL)
        entityDoc.open(completionHandler: { success in
            if !success {
                print("DisplayMembersInteractor: fetchMembers: error opening EntityDocument")
            }
            else {
                
                if entityDoc.entity!.members == nil {
                    entityDoc.entity!.members = [Member]()
                }
                entityDoc.entity?.members?.append(member)
                entityDoc.updateChangeCount(.done)
                entityDoc.close(completionHandler: { success in
                    print(entityDoc)
                    callback()
                })
            }
        })
    }
 
}
