//
//  EditEventPresenter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 6/10/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditEventPresentationLogic {
//    func presentSomething(response: EditEvent.Something.Response)
}

class EditEventPresenter: EditEventPresentationLogic {
    weak var viewController: EditEventDisplayLogic?

    // MARK: Do something
//
//    func presentSomething(response: EditEvent.Something.Response) {
//        let viewModel = EditEvent.Something.ViewModel()
//        viewController?.displaySomething(viewModel: viewModel)
//    }
}
