//
//  DisplaySubEntitiesPresenter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 8/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DisplaySubEntitiesPresentationLogic {
    func presentSubEntities(response: DisplaySubEntities.SubEntities.Response)
}


class DisplaySubEntitiesPresenter: DisplaySubEntitiesPresentationLogic {
    weak var viewController: DisplaySubEntitiesDisplayLogic?

    // MARK: VIP

    func presentSubEntities(response: DisplaySubEntities.SubEntities.Response) {
        var subEntityNames = [String]()
        if let subEntities = response.subEntities {
            for subEntity in subEntities {
                let name = (subEntity.name ?? "")
                subEntityNames.append(name)
            }
        }
        let viewModel = DisplaySubEntities.SubEntities.ViewModel(subEntityNames: subEntityNames)
        viewController?.displaySubEntities(viewModel: viewModel)
    }
}
