//
//  DisplaySubEntitiesViewController.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 8/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DisplaySubEntitiesDisplayLogic: class {
    func displaySubEntities(viewModel: DisplaySubEntities.SubEntities.ViewModel)
}



class DisplaySubEntitiesViewController: UITableViewController, DisplaySubEntitiesDisplayLogic, DisplayDetailViewControllerDelegate, DisplayDetailViewControllerEditDelegate {
    var interactor: DisplaySubEntitiesBusinessLogic?
    var router: (NSObjectProtocol & DisplaySubEntitiesRoutingLogic & DisplaySubEntitiesDataPassing)?
    var subEntityNames = [String]()
    var subEntitySelected = false
    
    
    // MARK: - Storyboard actions
    
    @IBAction func addSubEntity(_ sender: Any) {
        router?.routeToAddSubEntity()
    }
    
    
    // MARK: - Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
  
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: - Setup

    private func setup() {
        let viewController = self
        let interactor = DisplaySubEntitiesInteractor()
        let presenter = DisplaySubEntitiesPresenter()
        let router = DisplaySubEntitiesRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: - Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
  
  // MARK: - View lifecycle
  
    override func viewDidLoad() {
        super.viewDidLoad()
    }


    /*
     Adjust tab bar of original UITabBarController once views have loaded
     */
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        guard let tabBarCont = UIApplication.shared.keyWindow?.rootViewController as? UITabBarController else {
            print("DisplaySubEntitiesViewController: could not get UITabBarController")
            return
        }
        
        let splitVC = splitViewController
        let detailVC = splitVC?.viewControllers[1] as? DisplayDetailViewController
        let detailVCView = detailVC?.view
        let tbFrame = tabBarCont.tabBar.frame
        tabBarCont.tabBar.frame = CGRect(x: (detailVCView?.frame.origin.x)!, y: tbFrame.origin.y, width: (detailVCView?.frame.size.width)!, height: tbFrame.size.height)
        
        detailVC!.delegate = self
        detailVC?.editDelegate = self
        detailVC!.detailLabel.text = "Select an entity  〉"
        detailVC!.detailLabel.textAlignment = .left
        detailVC!.detailButton.isHidden = false
        detailVC!.detailButton.setTitleColor(UIColor(white: 0.3, alpha: 0.5), for: .normal)
        detailVC!.detailButton.setTitle("No entity selected", for: UIControlState.normal)
        router?.updateDetailVC()
    }


    // MARK: - VIP
    
    func fetchSubEntities(entity: Entity) {
        let request = DisplaySubEntities.SubEntities.Request(entity: entity)
        interactor?.fetchSubEntities(request: request)
    }
    
    
    func displaySubEntities(viewModel: DisplaySubEntities.SubEntities.ViewModel) {
        subEntityNames = viewModel.subEntityNames!
        tableView.reloadData()
        interactor?.setCurrentSubEntity(index: 0)
        router!.updateDetailVC()
    }
    
    func refreshAfterAddingSubEntity() {
        interactor!.refreshSubEntities()
    }
    
    
    func refreshAfterEditingSubEntity() {
        interactor!.refreshSubEntities()
    }
    
    
    // MARK: - UITableViewDataSource methods
    
    override func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    
    /*
     Return number of rows equal to number of sub-entities.
     If there are no names, return 1 row so can display a message.
     */
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if subEntityNames.count == 0 && subEntitySelected {
            return 1
        }
        return subEntityNames.count
    }
    
    
    /*
     If there are no member in the selected entity, display a prompt on the first line.
     Otherwise display the members
     */
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "SubEntitiesMasterCell", for: indexPath)
        if subEntityNames.count == 0 && subEntitySelected {
            cell.textLabel?.text = "Add sub-entities"
            cell.textLabel?.textAlignment = .center
            cell.textLabel?.textColor = UIColor(white: 0.5, alpha: 0.7)
        }
        else {
            cell.textLabel?.text = subEntityNames[indexPath.row]
            cell.textLabel?.textAlignment = .left
            cell.textLabel?.textColor = UIColor.black
        }
        return cell
    }
    
    
    // MARK: - UITableViewDelegate methods
    
    override func tableView(_ tableView: UITableView, willSelectRowAt indexPath: IndexPath) -> IndexPath? {
        interactor?.setCurrentSubEntity(index: indexPath.row)
        router!.updateDetailVC()
        return indexPath
    }
    
    
    // MARK: - DisplayDetailViewControllerDelegate methods
    
    func didSelectEntityInDisplayDetailViewController(entity: Entity) {
        dismiss(animated: true, completion: nil)
        subEntitySelected = true
        fetchSubEntities(entity: entity)
    }
 
    
    // MARK: - DisplayDetailViewControllerEditDelegate methods
    
    func didPressEditButtonInDisplayDetailViewController(selectedItem: AnyObject?) {
        if selectedItem is SubEntity {
            router!.routeToEditSubEntity()
        }
    }
    
}
