//
//  DisplaySubEntitiesModels.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 8/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DisplaySubEntities {
  // MARK: Use cases
  
  enum SubEntities {
    struct Request {
        var entity: Entity?
    }
    struct Response {
        var subEntities: [SubEntity]?
    }
    struct ViewModel {
        var subEntityNames: [String]?
    }
  }
}
