//
//  AddEventInteractor.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 15/09/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddEventBusinessLogic {
    func saveEventToDisk(event: Event, callback: @escaping ()->())
}

protocol AddEventDataStore {
  //var name: String { get set }
}



class AddEventInteractor: AddEventBusinessLogic, AddEventDataStore {
    var presenter: AddEventPresentationLogic?

    
    func saveEventToDisk(event: Event, callback: @escaping ()->()) {
        guard let documentsDirectory = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            print("Error: Document directory not found")
            return
        }
        var filename: String
        if event.filename == nil {
            let formatter = DateFormatter()
            formatter.dateFormat = "yyyyMMdd_hh-mm"
            filename = formatter.string(from: Date())
        }
        else { filename = event.filename!}
        let docFileURL =  documentsDirectory.appendingPathComponent(filename + ".evt")
        let eventDoc = EventDocument(fileURL: docFileURL, name: event.filename, event: event)
        eventDoc.save(to: docFileURL, for: .forCreating, completionHandler: { success in
            if !success {
                print("AddEventInteractor: saveEntityToDisk: Error saving")
            }
            else{
                callback()
            }
        })
    }
}
