//
//  RemoveEntityPresenter.swift
//  SpeakerTracker
//
//  Created by Warwick McNaughton on 1/10/18.
//  Copyright (c) 2018 Warwick McNaughton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RemoveEntityPresentationLogic {
 //   func presentSomething(response: RemoveEntity.Something.Response)
}

class RemoveEntityPresenter: RemoveEntityPresentationLogic {
    weak var controller: RemoveEntityDisplayLogic?

    // MARK: Do something

//    func presentSomething(response: RemoveEntity.Something.Response) {
//        let viewModel = RemoveEntity.Something.ViewModel()
//        controller?.displaySomething(viewModel: viewModel)
//    }
}
